### ISSUE TITLE
Button Component: Font Size

### ISSUE THREAD

**Issue by alexnatalia** [soramitsu/soramitsu-js-ui-library#223]
There are 4 sizes for button component, but only one font size for all of them. Because of it the button with small/mini size looks buggy. Could we add appropriate font sizes for them?

<img width="380" alt="Screen Shot 2021-06-15 at 22 23 01" src="https://user-images.githubusercontent.com/38787212/122111334-49f8fc00-ce28-11eb-9860-7040c1a27ba4.png">

**Comment by stefashkaa** [comment]
@alexnatalia seems that we've fixed this issue, please check it again and close if it was resolved.
