### ISSUE TITLE
Tabs Component: Active item text color the same with background

### ISSUE THREAD

**Issue by alexnatalia** [soramitsu/soramitsu-js-ui-library#224]
There is a small issue with active tab item for Neumorphic design system.
To reproduce the issue you should set _accent-rounded_ as tabs type and check active item.

<img width="392" alt="Screen Shot 2021-06-15 at 22 29 48" src="https://user-images.githubusercontent.com/38787212/122112205-3bf7ab00-ce29-11eb-94ba-3fdc0626a619.png">

**Comment by stefashkaa** [comment]
@alexnatalia this type of tabs shouldn't be used with neumorphic theme. We've added `type="rounded"` by default
