### ISSUE TITLE
Fix neumorphism expanded collapse component arrow shadow direction

### ISSUE THREAD

**Issue by shlavik** [soramitsu/soramitsu-js-ui-library#437]
Hello, devs!

I'm Polkaswap user, and came here because annoyed by wrong direction of arrow shadow of expanded collapse component

Neomorphism assumes that global direction of shadow (and light source) remains unchanged, and such shortcomings hurt eyes of perfectionists like me 😁

![image](https://user-images.githubusercontent.com/2076748/177081784-00b06df6-1370-4ed4-b74e-7beecbd69ce1.png)

**Comment by stefashkaa** [comment]
@shlavik hey! will be fixed here #505
